---
- hosts: all
  become: true
  vars:
    POSTGRESQL_CONFIGURATION:
      - name: max_connections
        value: 160
      - name: shared_buffers
        value: 134MB
      - name: huge_pages
        value: off
      - name: work_mem
        value: 32MB
      - name: maintenance_work_mem
        value: 320MB
      - name: bgwriter_delay
        value: 200ms
      - name: bgwriter_lru_maxpages
        value: 100
      - name: bgwriter_lru_multiplier
        value: 2.0
      - name: bgwriter_flush_after
        value: 0
      - name: effective_io_concurrency
        value: 2
      - name: maintenance_io_concurrency
        value: 10
      - name: max_worker_processes
        value: 8
      - name: max_parallel_workers_per_gather
        value: 4
      - name: max_parallel_maintenance_workers
        value: 4
      - name: max_parallel_workers
        value: 8
      - name: wal_level
        value: minimal
      - name: synchronous_commit
        value: on 
      - name: wal_compression
        value: on
      - name: wal_buffers
        value: -1
      - name: wal_writer_delay
        value: 200ms
      - name: wal_writer_flush_after
        value: 1MB
      - name: max_wal_size
        value: 1GB
      - name: min_wal_size
        value: 512MB
      - name: max_wal_senders
        value: 0
      - name: enable_partitionwise_join
        value: on
      - name: enable_partitionwise_aggregate
        value: on
      - name: random_page_cost
        value: 4.0
      - name: effective_cache_size
        value: 3GB
      - name: default_statistics_target
        value: 100
      - name: jit
        value: on
  roles:
    - { role: postgresql, tags: [postgresql-installation, postgresql-configuration] }
    - pgbouncer
